### PR TITLE
Add Mumbai and Telegram messaging support

### PR DESCRIPTION
**Pull request by theIYD**
For Hyderabad and Bangalore an email is sent, here in Mumbai a message on Telegram is sent.

PS: IMAX Screen in Mumbai is going full instantly. Needed this. A great open source project xD

### CODE REVIEW

**Comment by reeversedev** [comment]
Thanks @theIYD . I didn't know this can be important for someone. I'll build more stuff in this. 

If you'd like to contribute in any manner, please do. We can always about ideas.

**Comment by reeversedev** [comment]
@theIYD Also, I used constants for my own usage. Definitely, not a good approach. Probably the worst because I was just using it for testing on a short notice.

**Comment by theIYD** [comment]
@reeversedev Can we connect over telegram or hangouts ?

**Comment by reeversedev** [comment]
Yeah sure. You can DM me on twitter as well. @reeversedev on twitter.

**Pull request closed without merging**
